### PR TITLE
Resolve issue 4 - dynamically detect what to bring based on the weather

### PR DESCRIPTION
**Pull request by cyu60**

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@JuliaS96 Please, review this pull request

**Comment by JuliaS96** [comment]
Hello @cyu60 , a few comments:
- please omit the yarn.lock and package-lock.json files
- could you add also a check based on temperature? please see below for example of use case
Screenshot 2023-04-13 at 12 26 54 PM
- i think there's some additional weather codes that we haven't included. Please see 7XX. Perhaps a warning  ("Please avoid going outside") for some of them i.e. Tornado - 781. https://openweathermap.org/weather-conditions

**Comment by grace-omotoso** [comment]
@cyu60 here is a guideline that can be used for items to bring
const requiredThings = {
	Thunderstorm: {
		Raincoat: Raincoat,
		Flashlight: Flashlight,
		'Waterproof Boots': WaterproofBoots,
	},
	Drizzle: {
		Raincoat: Raincoat,
		'Waterproof Boots': WaterproofBoots,
		Umbrella: Umbrella,
	},
	Rain: {
		Raincoat: Raincoat,
		'Waterproof Boots': WaterproofBoots,
		Umbrella: Umbrella,
	},
	Snow: {
		Googles: Googles,
		Gloves: Gloves,
		Jacket: Jacket,
	},
	Mist: {
		Watch: Watch,
		Googles: Googles,
		Mask: Mask,
	},
	Smoke: {
		Watch: Watch,
		Googles: Googles,
		Mask: Mask,
	},
	Haze: {
		Watch: Watch,
		Googles: Googles,
		Mask: Mask,
	},
	Dust: {
		'Face Wipes': Wipes,
		Googles: Googles,
		Mask: Mask,
	},
	Fog: {
		Watch: Watch,
		Googles: Googles,
		Mask: Mask,
	},
	Sand: {
		Mask: Mask,
		Googles: Googles,
		'Sand Scarf': SandScarf,
	},
	Ash: {
		'Face Wipes': Wipes,
		Googles: Googles,
		Mask: Mask,
	},
	Squall: {
		Watch: Watch,
		Googles: Googles,
		Mask: Mask,
	},
	Tornado: {
		Sanitation: Sanitation,
		Flashlight: Flashlight,
		Googles: Googles,
	},
	Clear: {
		Sunglasses: Sunglasses,
		BaseballCap: Cap,
		Sunscreen: Sunscreen,
	},
	Clouds: {
		BaseballCap: Cap,
		Watch: Watch,
		'Mosquito Repellent': MosquitoRepellent,
	},

	Sunny: {
		Sunglasses: Sunglasses,
		BaseballCap: Cap,
		Sunscreen: Sunscreen,
	},
};

**Comment by grace-omotoso** [comment]
@cyu60  @TynenW, this may be for a later version. Can you work with @hrl-2024 to display pictures of items instead of text?
items to bring

**Comment by cyu60** [comment]
Thanks a lot! I will make the updates this weekend.

**Comment by cyu60** [comment]
> Hello @cyu60 , a few comments:
> 
> * please omit the yarn.lock and package-lock.json files
> * could you add also a check based on temperature? please see below for example of use case
> 
> Screenshot 2023-04-13 at 12 26 54 PM
> 
> - i think there's some additional weather codes that we haven't included. Please see 7XX. Perhaps a warning ("Please avoid going outside") for some of them i.e. Tornado - 781. https://openweathermap.org/weather-conditions

How do I omit the yarn.lock and package-lock.json files now that they have already been commited?

**Comment by JuliaS96** [comment]
> 

@cyu60 sorry for the delay. This is how I did it, there might be better ways but it worked:
1. Connect your local repo to the upstream if you haven't and fetch: "git remote add upstream https://github.com/MLH-Fellowship/prep-project-23.APR.PREP.2.git"
2. Delete both files from your local repo / from the commit
3. Checkout only the yarn file into your repo: "git checkout upstream/main -- yarn.lock"
4. Commit the changes

**Comment by grace-omotoso** [comment]
@cyu60 please, fix merge conflicts

**Comment by JuliaS96** [comment]
I will work with Chinat to remove yarn.lock - otherwise good

**Pull request merged**
