### PR TITLE
Spotify 2.0

### PR DESCRIPTION
**Pull request by JuliaS96**
- All changes from main merged into the proper area
Also added:
- Spotify connection
- Right now, user can log in / log out and play a song / pause / play next songs
- Playlist updates when you change cities based on the current weather
- Other styling changes

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@cyu60 please, review this PR

**Comment by am831** [comment]
The spotify login doesn't work for me. It takes me to a blank page that isn't loading. I see on line 35 of MusicPlayer.jsx the url it is supposed to take me to, but it takes me here: 
https://accounts.spotify.com/en/login?continue=https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fscope%3Dstreaming%2B%2Buser-read-email%2Buser-read-private%2Buser-read-currently-playing%2Buser-read-recently-played%2Buser-read-playback-state%2Buser-top-read%2Buser-modify-playback-state%26response_type%3Dtoken%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A3000%26client_id%3Dundefined

Maybe client_id being undefined is the issue, I wonder if it only behaves like that in the deployment preview but works otherwise?

**Comment by JuliaS96** [comment]
Hey @am831 thanks for checking and yeah, I need Grace to put in the client ID in local variables on the netlify website, the branch isn't ready for review yet. I should've specified, I was waiting to bring it up in meeting :)

**Comment by JuliaS96** [comment]
synching up with Riley on Spotify issue

**Comment by grace-omotoso** [comment]
@hrl-2024 can you please review this PR?

**Pull request merged**
