### PR TITLE
Dynamically updating map location and only suggesting location with data

### PR DESCRIPTION
**Pull request by MargaretDiaz4570**
- The AutoComp.js file now has a filter that only suggests cities that have weather data
- The map component now passes in the inputted city as a prop and updates the location on the map
- The map component only lets users be able to successfully click and change location to cities with weather data
- Adding styling changes to the map to make it wider and have padding so it doesn't display directly next to the screen

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@MargaretDiaz4570 when a location is selected on the map, and we go back to the home page, the main weather card does not show the location, the old location is shown. Is this a fix you can make on your end or it will be better off with another PR? Just let me know

**Comment by hrl-2024** [comment]
Hi @grace-omotoso, the home screen is supposed to show your current location's and your favorite location's weather. To have the location you just searched to appear on the home page, you will need to favorite it. I think what you are suggesting is the last-searched location weather, which is not part of home screen's functionality. But aside from this, I think this PR looks great!

**Review by hrl-2024 — APPROVED** [review]
Changes looks great. Should be an easy task to put into the UI refractor

**Comment by grace-omotoso** [comment]
@MargaretDiaz4570 I saw Ruihang's comment. Could you please fix the merge conflict, then I will merge. Thanks

**Comment by MargaretDiaz4570** [comment]
I did another merge/upstream to resolve the conflicts it should be good to go now :)

**Pull request merged**
