### PR TITLE
feat: Implemented hourly forecast feature with chart.js

### LINKED ISSUE #1: Hourly Forecasts
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

### PR DESCRIPTION
**Pull request by mukhsadr**
### Commits:

- [x] chore: added calendar user input
- [x] feat: implemented hourly forecast feature with chart.js
- [x] feat: displayed today weather forecast data by default 
- [x] fix: corrected temperature unit conversion
- [x] refactor: optimized code for better performance by creating Forecast component 
- [x] docs: updated README file with library installation.

### For reviewers:

I would like to thank you for taking the time to review my pull request. I am open to any constructive feedback you may have regarding the changes made to the weather app. Your suggestions and comments will be greatly appreciated, and I will do my best to address them promptly. Thank you once again for your time and consideration.

Closes #1

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@hrl-2024 please, review this PR

**Comment by grace-omotoso** [comment]
@mukhsadr please, fix merge conflicts

**Comment by mukhsadr** [comment]
@grace-omotoso I just resolved the conflict with App.js

**Comment by hrl-2024** [comment]
Hi @mukhsadr, everything looks great. The background gif looks fancy. But it might add a little load time for the performance, and the current implementation look a bit different than in the design file. So I would suggest to make it look as close to the design file if possible?
And also, can you also remove the package-lock.json file from your commit as well?

**Review by hrl-2024 — APPROVED** [review]
File changes reviewed

**Comment by hrl-2024** [comment]
@grace-omotoso Hi Grace, changes look good to me. We can merge this PR now if no further commit happens after the previous comment "File changes reviewed."

**Comment by mukhsadr** [comment]
I wanted to thank you, @hrl-2024 for taking the time to review my pull request for the forecast feature. I appreciate your honest feedback and suggestions for improvement. I will definitely take them into consideration for future work.

Just wanted to let you, @grace-omotoso  know that the pull request for the forecast feature has been reviewed and is ready to be merged. @hrl-2024  has reviewed the changes and provided valuable feedback, which I have incorporated into the code. I believe everything is good to go and we can proceed with the merge.

Please let me know if you have any questions or concerns. Thanks!

**Pull request merged**
