### PR TITLE
refactor songrecs to a popup, but on another button 

### PR DESCRIPTION
**Pull request by MadaniKK**
Ruihang will help finish the rest of refactoring

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@MargaretDiaz4570 songs are no longer showing

**Comment by hrl-2024** [comment]
Hi Riley and Maggie, the pop up window is too small now that all of the songs got cramped together. I wonder if you can the pop up window bigger and also make your song cards wrapped around when the screen size changes.

**Comment by MadaniKK** [comment]
> Hi Riley and Maggie, the pop up window is too small now that all of the songs got cramped together. I wonder if you can the pop up window bigger and also make your song cards wrapped around when the screen size changes.

Now fixed! Thank you!!

**Review by cyu60 — COMMENTED** [review]
Looks good!

**Pull request merged**
